apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderlust-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: wanderlust-backend
  template:
    metadata:
      labels:
        app: wanderlust-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: PORT
              value: {{ .Values.backend.env.PORT | quote }}
            - name: MONGODB_URI
              value: {{ .Values.backend.env.MONGODB_URI | quote }}
            - name: REDIS_URL
              value: {{ .Values.backend.env.REDIS_URL | quote }}
            - name: FRONTEND_URL
              value: {{ .Values.backend.env.FRONTEND_URL | quote }}
            - name: BACKEND_URL
              value: {{ .Values.backend.env.BACKEND_URL | quote }}
            - name: NODE_ENV
              value: {{ .Values.backend.env.NODE_ENV | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wanderlust-backend-secret
                  key: JWT_SECRET
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: wanderlust-backend-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wanderlust-backend-secret
                  key: GOOGLE_CLIENT_SECRET
